services:
  selenium-hub:
    image: selenium/hub:4.39.0
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      SE_LOG_LEVEL: INFO

  chrome:
    image: selenium/node-chrome:4.39.0
    container_name: node-chrome
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 2
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_LOG_LEVEL: INFO
    volumes:
      - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox:4.39.0
    container_name: node-firefox
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 2
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_LOG_LEVEL: INFO
    volumes:
      - /dev/shm:/dev/shm

  edge:
    image: selenium/node-edge:4.39.0
    container_name: node-edge
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_MAX_SESSIONS: 2
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_LOG_LEVEL: INFO
    volumes:
      - /dev/shm:/dev/shm

